spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
          discovery:
            locator:
                enabled: true  # Enables dynamic routing with service discovery
          routes:
              - id: USER-SERVICE
                uri: lb://USER-SERVICE
                predicates:
                  - Path=/users/**,/staff/**

              - id: user-service
                uri: lb://HOTEL-SERVICE
                predicates:
                  - Path=/hotel/**

              - id: RATTING-SERVICE
                uri: lb://RATTING-SERVICE
                predicates:
                  - Path=/ratting/**

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://localhost:8761/eureka


